name: QEMU

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "20250317"

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          sudo sed -i 's,Types: deb,Types: deb deb-src,' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          sudo apt-get install -y devscripts
          mkdir build
          cd build
          sudo apt-get build-dep -y qemu
          apt-get source qemu
          cd qemu-*
          for file in ../../.github/patches/qemu/*.patch; do
            patch -p1 < $file
          done
          export DEBFULLNAME="Ole André Vadla Ravnås"
          export DEBEMAIL="oleavr@frida.re"
          dch --local frida "Apply patches needed for Frida's use-cases."
          dpkg-buildpackage -uc -us -b
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: "Roll packages."
          files: build/*.deb
